
name: RP2

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
on:
  push:
    paths-ignore:
      - 'examples/**'
      - 'README.md'
      - 'ci/*unix*.sh'
      - '.github/workflows/build_unix.yml'
      - '.github/workflows/build_esp32.yml'
  pull_request:
    paths-ignore:
      - 'examples/**'
      - 'README.md'
      - 'ci/*unix*.sh'
      - '.github/workflows/build_unix.yml'
      - '.github/workflows/build_esp32.yml'

jobs:
  tensorflow_micropython_rp2_build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Pillow & Wave
        run: |
          pip install Pillow
          pip3 install Wave
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare to Build Tensorflow Micropython Firmware for RP2
        run: |
          git submodule init
          git submodule update --recursive
          cd micropython
          git submodule update --init lib/pico-sdk lib/tinyusb
          cd ..
      - name: Get Cache Keys
        run: |
          TFLM_COMMIT=$(git submodule status tensorflow | awk '{print ($1)}')
          echo "tflm-commit=$TFLM_COMMIT" >> $GITHUB_ENV
      - name: Setup GCC ARM
        run: |
          source ./micropython/tools/ci.sh && ci_rp2_setup

#      - name: Cache tflm
#        id: cache-tflm
#        uses: actions/cache@v2
#        env:
#          cache-name: cache-rp2-tflm
#        with:
#          path: ./micropython-modules/microlite/tflm
#          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.tflm-commit }}
      - name: Setup Build for Tensorflow
#        if: steps.cache-tflm.outputs.cache-hit != 'true'
        run: |

          echo "Regenerating microlite/tfm directory"
          rm -rf ./micropython-modules/microlite/tflm

          cd ./tensorflow

          ../micropython-modules/microlite/prepare-tflm-rp2.sh

      - name: Build micropython cross compiler
        run:  |
          cd ./micropython
          make -C ports/rp2 submodules
          echo "make -C mpy-cross V=1 clean all"
          make -C mpy-cross V=1 clean all
      - name: Build RP2
        run: |

          cd micropython-modules
          ln -s ../micropython-ulab/code  ulab
          cd ../micropython

          # the pico_board needs to point at the name that exists in the pico sdk.
          # for us we just need our build files
          cmake -S ports/rp2 -B build-rp2-microlite -DPICO_BUILD_DOCS=0 -DMICROPY_BOARD=ADAFRUIT_FEATHER_RP2040 \
          -DUSER_C_MODULES=/home/runner/work/tensorflow-micropython-examples/tensorflow-micropython-examples/micropython-modules/micropython.cmake


          cd build-rp2-microlite

          make

      - name: Archive ADAFRUIT_FEATHER_RP2040_MICROLITE firmware
        uses: actions/upload-artifact@v2
        with:
          name: microlite-rp2-adafruit-feather-rp2040-firmware
          path: |
            micropython/build-rp2-microlite/firmware.elf
            micropython/build-rp2-microlite/firmware.bin
            micropython/build-rp2-microlite/firmware.dis
            micropython/build-rp2-microlite/firmware.elf.map
            micropython/build-rp2-microlite/firmware.hex
            micropython/build-rp2-microlite/firmware.uf2
