
name: ESP32

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
on: [push, pull_request]

jobs:
  esp32_tensorflow_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Tensorflow static library for ESP32
        run: |
          git submodule init
          git submodule update --recursive
          docker run --rm -v `pwd`:/opt/tflite-micro-micropython espressif/idf:release-v4.3 /opt/tflite-micro-micropython/ci/build_tensorflow_esp32.sh
      - name: Build Tensorflow Micropython Firmware for ESP32
        run: |
          cd micropython
          git submodule update --init lib/axtls
          git submodule update --init lib/berkeley-db-1.xx
          cd ..
          docker run --rm -v `pwd`:/opt/tflite-micro-micropython espressif/idf:release-v4.3 /opt/tflite-micro-micropython/ci/build_micropython_esp32.sh
      - name: Archive ESP32-MICROLITE firmware
        uses: actions/upload-artifact@v2
        with:
          name: microlite-esp32-firmware.bin
          path: micropython/ports/esp32/build-MICROLITE/firmware.bin
      - name: Archive ESP32-MICROLITE-SPIRAM-16M firmware
        uses: actions/upload-artifact@v2
        with:
          name: microlite-spiram-16m-esp32-firmware.bin
          path: micropython/ports/esp32/build-MICROLITE_SPIRAM_16M/firmware.bin
