
name: RP2

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
on:
  push:
    paths-ignore:
      - 'examples/**'
      - 'README.md'
      - 'ci/*unix*.sh'
      - '.github/workflows/build_unix.yml'
      - '.github/workflows/build_esp32.yml'
  pull_request:
    paths-ignore:
      - 'examples/**'
      - 'README.md'
      - 'ci/*unix*.sh'
      - '.github/workflows/build_unix.yml'
      - '.github/workflows/build_esp32.yml'

jobs:
  tensorflow_micropython_rp2_build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Pillow & Wave
        run: |
          pip install Pillow
          pip3 install Wave
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare to Build Tensorflow Micropython Firmware for RP2
        run: |
          git submodule init
          git submodule update --recursive
          cd micropython
          git submodule update --init lib/pico-sdk lib/tinyusb
          cd ..
      - name: Get Cache Keys
        run: |
          TFLM_COMMIT=$(git submodule status tensorflow | awk '{print ($1)}')
          echo "tflm-commit=$TFLM_COMMIT" >> $GITHUB_ENV
      - name: Setup GCC ARM
        run: |
          source ./micropython/tools/ci.sh && ci_rp2_setup

      - name: Cache tflm
        id: cache-tflm
        uses: actions/cache@v2
        env:
          cache-name: cache-rp2-tflm
        with:
          path: ./micropython-modules/microlite/tflm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.tflm-commit }}
      - name: Setup Build for Tensorflow
        if: steps.cache-tflm.outputs.cache-hit != 'true'
        run: |

          echo "Regenerating microlite/tfm directory"
          rm -rf ./micropython-modules/microlite/tflm

          cd ./tensorflow

          python3 ./tensorflow/lite/micro/tools/project_generation/create_tflm_tree.py \
          --makefile_options="TARGET=cortex_m_generic TARGET_ARCH=project_generation OPTIMIZED_KERNEL_DIR=cmsis_nn" \
          --examples micro_speech --rename-cc-to-cpp ../micropython-modules/microlite/tflm

      - name: Build micropython cross compiler
        run:  |
          cd ./micropython
          make -C ports/rp2 submodules
          echo "make -C mpy-cross V=1 clean all"
          make -C mpy-cross V=1 clean all
      - name: Build RP2
        run: |

          cd micropython-modules
          ln -s ../micropython-ulab/code  ulab
          cd ../micropython

          # the pico_board needs to point at the name that exists in the pico sdk.
          # for us we just need our build files
          cmake -S ports/rp2 -B build-ADAFRUIT_FEATHER_RP2040_MICROLITE -DPICO_BUILD_DOCS=0 \
          -DMICROPY_BOARD=ADAFRUIT_FEATHER_RP2040_MICROLITE \
          -DMICROPY_BOARD_DIR=/home/mike/git/tensorflow-micropython-examples/boards/rp2/ADAFRUIT_FEATHER_RP2040_MICROLITE \
          -DPICO_BOARD=adafruit_feather_rp2040

      - name: Archive ADAFRUIT_FEATHER_RP2040_MICROLITE firmware
        uses: actions/upload-artifact@v2
        with:
          name: microlite-rp2-adafruit-feather-rp2040-firmware
          path: |
            boards/rp2/ADAFRUIT_FEATHER_RP2040_MICROLITE/build/firmware.elf
            boards/rp2/ADAFRUIT_FEATHER_RP2040_MICROLITE/build/firmware.bin
            boards/rp2/ADAFRUIT_FEATHER_RP2040_MICROLITE/build/firmware.dfu
            boards/rp2/ADAFRUIT_FEATHER_RP2040_MICROLITE/build/firmware.hex
            boards/rp2/ADAFRUIT_FEATHER_RP2040_MICROLITE/build/bootloader/bootloader.bin
            boards/rp2/ADAFRUIT_FEATHER_RP2040_MICROLITE/build/partition_table/partition-table.bin
            boards/rp2/ADAFRUIT_FEATHER_RP2040_MICROLITE/build/micropython.bin
