
name: ESP32

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
on:
  push:
  pull_request:
    paths-ignore:
      - 'examples/**'
      - 'README.md'
      - 'ci/*unix*.sh'
      - '.github/workflows/build_unix.yml'

jobs:
  tensorflow_micropython_esp32_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare to Build Tensorflow Micropython Firmware for ESP32
        run: |
          git submodule init
          git submodule update --recursive
          cd micropython
          git submodule update --init lib/axtls
          git submodule update --init lib/berkeley-db-1.xx
          cd ..
      - name: Setup IDF
        run: source ./micropython/tools/ci.sh && ci_esp32_idf43_setup
      - name: Build standard non-psram 4MB Flash firmware
        run: |
          source ./ci/setup_esp32.sh && ci_setup_microlite
          ./ci/build_micropython_esp32_microlite.sh
      - name: Archive ESP32-MICROLITE firmware
        uses: actions/upload-artifact@v2
        with:
          name: microlite-esp32-firmware
          path: |
            boards/esp32/MICROLITE/build/bootloader/bootloader.bin
            boards/esp32/MICROLITE/build/partition_table/partition-table.bin
            boards/esp32/MICROLITE/build/micropython.bin
      - name: Build with psram support and 16MB Flash firmware
        run: |
          docker run --rm -v `pwd`:/opt/tflite-micro-micropython espressif/idf:release-v4.3 /opt/tflite-micro-micropython/ci/build_micropython_esp32_microlite_spiram_16m.sh      
      - name: Archive ESP32-MICROLITE-SPIRAM-16M firmware
        uses: actions/upload-artifact@v2
        with:
          name: microlite-spiram-16m-esp32-firmware
          path: |
            boards/esp32/MICROLITE_SPIRAM_16M/build/bootloader/bootloader.bin
            boards/esp32/MICROLITE_SPIRAM_16M/build/partition_table/partition-table.bin
            boards/esp32/MICROLITE_SPIRAM_16M/build/micropython.bin
