
name: ARM Tensorflow Micro

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
on:
  push:
  pull_request:
    paths-ignore:
      - 'examples/**'
      - 'README.md'
      - 'ci/*unix*.sh'
      - '.github/workflows/build_unix.yml'
      - '.github/workflows/build_esp32.yml'

jobs:
  tensorflow_arm_build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Pillow
        run: |
          pip install Pillow
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Tensorflow static library for ARM
        run: |
          git submodule init
          git submodule update --recursive
          chmod +x ./ci/build_tensorflow_cortex_m_generic.sh
          ./ci/build_tensorflow_cortex_m_generic.sh

